#ifndef GRAMMAR_H
#define GRAMMAR_H

typedef enum {
  NUMBER, STRING_LITERAL,
  UNARY_FLIP_OP,PLUS_OP,
  MINUS_OP,PRODUCT_OP, 
  DIVIDE_OP,POWER_OP, 
  ASSIGNMENT_OP,MODULUS_OP, 
  SEMICOLON, RESERVED_WORD,
  NAMED_LEXEME, LEFT_BRACE, 
  RIGHT_BRACE, FLOOR_DIV_OP,
  LINE_END,UNARY_PLUS_OP,
  UNARY_MINUS_OP, LOG_AND_OP,
  LOG_OR_OP, LOG_NOT_OP,
  LOG_XOR_OP, BIT_AND_OP,
  BIT_OR_OP,BIT_XOR_OP,
  ARITH_LSHIFT, ARITH_RSHIFT
} Tokens;


// reserved word
#define RESERVED_WORD_VAR "var"
#define RESERVED_WORD_CONST "const"
#define RESERVED_WORD_NULL "Null"

#define NAMED_OPERATOR_MODULO "mod"
#define NAMED_OPERATOR_AND "and"
#define NAMED_OPERATOR_OR "or"
#define NAMED_OPERATOR_NOT "not"
#define NAMED_OPERATOR_XOR "xor"

#endif

