#ifndef GRAMMAR_H
#define GRAMMAR_H

typedef enum {
  NUMBER, STRING_LITERAL,
  UNARY_FLIP_OP,PLUS_OP,
  MINUS_OP,PRODUCT_OP, 
  DIVIDE_OP,POWER_OP, 
  ASSIGNMENT_OP,MODULUS_OP, 
  SEMICOLON, RESERVED_WORD,
  NAMED_LEXEME, LEFT_BRACE, 
  RIGHT_BRACE, FLOOR_DIV_OP,
  LINE_END,UNARY_PLUS_OP,
  UNARY_MINUS_OP, LOG_AND_OP,
  LOG_OR_OP, LOG_NOT_OP,
  LOG_XOR_OP, BIT_AND_OP,
  BIT_OR_OP,BIT_XOR_OP,
  ARITH_LSHIFT, ARITH_RSHIFT,
  DYNAMIC_LIST_LEFT_BRACE,
  DYNAMIC_LIST_RIGHT_BRACE,
  GREATER_THAN_OP, LESS_THAN_OP,
  GREATER_THAN_OR_EQUAL_OP, LESS_THAN_OR_EQUAL_OP,
  EQUALITY_OP,NOT_EQUAL_OP,COMMA,
  MAP_BRACE,RETURN_OPERATOR
} Tokens;

// reserved word
#define RESERVED_WORD_VAR "var"
#define RESERVED_WORD_CONST "const"
#define RESERVED_WORD_NULL "Null"
#define RESERVED_WORD_DO "do"
#define RESERVED_WORD_DONE "done"
#define RESERVED_WORD_IF "if"
#define RESERVED_WORD_ELSE "else"
#define RESERVED_WORD_FUNCDEF "funcdef"
#define RESERVED_WORD_ENUM "enum"

#define NAMED_OPERATOR_MODULO "mod"
#define NAMED_OPERATOR_AND "and"
#define NAMED_OPERATOR_OR "or"
#define NAMED_OPERATOR_NOT "not"
#define NAMED_OPERATOR_XOR "xor"

#endif

